name: "Upload File Action"
description: "A GitHub Action to upload files"
author: "Hasura"

branding:
  icon: "upload"
  color: "blue"

inputs:
  file_path:
    description: "Path to the file to upload"
    required: true
  destination:
    description: "Destination path in security agent storage bucket"
    required: false
  security_agent_api_endpoint:
    description: "Security Agent API endpoint"
    required: false
    default: https://security-agent.ddn.pro.hasura.io/graphql
  security_agent_api_key:
    description: "Security Agent API key"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
