name: Test Upload File Action

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "This is a test file created at $(date)" > test-upload.txt
          echo "GitHub SHA: ${{ github.sha }}" >> test-upload.txt

      - name: Test upload action
        id: upload-test
        uses: ./upload-file
        with:
          file_path: "./test-upload.txt"
          destination: "https://httpbin.org/post"

      - name: Verify upload completed
        run: |
          echo "Upload test completed successfully!"
